//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Poker_MsgPokerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Poker.MsgPoker), typeof(System.Object));
		L.RegFunction("SetCmd", SetCmd);
		L.RegFunction("SetStatus", SetStatus);
		L.RegFunction("SetBody", SetBody);
		L.RegFunction("New", _CreatePoker_MsgPoker);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreatePoker_MsgPoker(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Poker.MsgPoker obj = new Poker.MsgPoker();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Poker.MsgPoker.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetCmd(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Poker.MsgPoker obj = (Poker.MsgPoker)ToLua.CheckObject(L, 1, typeof(Poker.MsgPoker));
			ushort arg0 = (ushort)LuaDLL.luaL_checknumber(L, 2);
			obj.SetCmd(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetStatus(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Poker.MsgPoker obj = (Poker.MsgPoker)ToLua.CheckObject(L, 1, typeof(Poker.MsgPoker));
			ushort arg0 = (ushort)LuaDLL.luaL_checknumber(L, 2);
			obj.SetStatus(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetBody(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(Poker.MsgPoker), typeof(LuaInterface.LuaByteBuffer)))
			{
				Poker.MsgPoker obj = (Poker.MsgPoker)ToLua.ToObject(L, 1);
				LuaByteBuffer arg0 = new LuaByteBuffer(ToLua.CheckByteBuffer(L, 2));
				obj.SetBody(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(Poker.MsgPoker), typeof(byte[])))
			{
				Poker.MsgPoker obj = (Poker.MsgPoker)ToLua.ToObject(L, 1);
				byte[] arg0 = ToLua.CheckByteBuffer(L, 2);
				obj.SetBody(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Poker.MsgPoker.SetBody");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

