-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('response.Res_PlayerMsg_pb')


local PLAYER = protobuf.Descriptor();
local PLAYER_NAME_FIELD = protobuf.FieldDescriptor();
local PLAYER_GOLD_FIELD = protobuf.FieldDescriptor();
local PLAYER_SYCEE_FIELD = protobuf.FieldDescriptor();
local PLAYER_STONE_FIELD = protobuf.FieldDescriptor();

PLAYER_NAME_FIELD.name = "name"
PLAYER_NAME_FIELD.full_name = ".com.sojoys.chess.game.protobuf.response.Player.name"
PLAYER_NAME_FIELD.number = 1
PLAYER_NAME_FIELD.index = 0
PLAYER_NAME_FIELD.label = 2
PLAYER_NAME_FIELD.has_default_value = false
PLAYER_NAME_FIELD.default_value = ""
PLAYER_NAME_FIELD.type = 9
PLAYER_NAME_FIELD.cpp_type = 9

PLAYER_GOLD_FIELD.name = "gold"
PLAYER_GOLD_FIELD.full_name = ".com.sojoys.chess.game.protobuf.response.Player.gold"
PLAYER_GOLD_FIELD.number = 2
PLAYER_GOLD_FIELD.index = 1
PLAYER_GOLD_FIELD.label = 2
PLAYER_GOLD_FIELD.has_default_value = false
PLAYER_GOLD_FIELD.default_value = 0
PLAYER_GOLD_FIELD.type = 3
PLAYER_GOLD_FIELD.cpp_type = 2

PLAYER_SYCEE_FIELD.name = "sycee"
PLAYER_SYCEE_FIELD.full_name = ".com.sojoys.chess.game.protobuf.response.Player.sycee"
PLAYER_SYCEE_FIELD.number = 3
PLAYER_SYCEE_FIELD.index = 2
PLAYER_SYCEE_FIELD.label = 2
PLAYER_SYCEE_FIELD.has_default_value = false
PLAYER_SYCEE_FIELD.default_value = 0
PLAYER_SYCEE_FIELD.type = 3
PLAYER_SYCEE_FIELD.cpp_type = 2

PLAYER_STONE_FIELD.name = "stone"
PLAYER_STONE_FIELD.full_name = ".com.sojoys.chess.game.protobuf.response.Player.stone"
PLAYER_STONE_FIELD.number = 4
PLAYER_STONE_FIELD.index = 3
PLAYER_STONE_FIELD.label = 2
PLAYER_STONE_FIELD.has_default_value = false
PLAYER_STONE_FIELD.default_value = 0
PLAYER_STONE_FIELD.type = 3
PLAYER_STONE_FIELD.cpp_type = 2

PLAYER.name = "Player"
PLAYER.full_name = ".com.sojoys.chess.game.protobuf.response.Player"
PLAYER.nested_types = {}
PLAYER.enum_types = {}
PLAYER.fields = {PLAYER_NAME_FIELD, PLAYER_GOLD_FIELD, PLAYER_SYCEE_FIELD, PLAYER_STONE_FIELD}
PLAYER.is_extendable = false
PLAYER.extensions = {}

Player = protobuf.Message(PLAYER)

