-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('DemoMsg_pb')


local DEMOREQUEST = protobuf.Descriptor();
local DEMOREQUEST_IP_FIELD = protobuf.FieldDescriptor();
local DEMOREQUEST_ACCOUNTID_FIELD = protobuf.FieldDescriptor();
local DEMOREQUEST_SERVERID_FIELD = protobuf.FieldDescriptor();
local DEMORESPONSE = protobuf.Descriptor();
local DEMORESPONSE_NAME_FIELD = protobuf.FieldDescriptor();
local DEMORESPONSE_LVL_FIELD = protobuf.FieldDescriptor();

DEMOREQUEST_IP_FIELD.name = "IP"
DEMOREQUEST_IP_FIELD.full_name = ".com.demo.protobuf.DemoRequest.IP"
DEMOREQUEST_IP_FIELD.number = 1
DEMOREQUEST_IP_FIELD.index = 0
DEMOREQUEST_IP_FIELD.label = 2
DEMOREQUEST_IP_FIELD.has_default_value = false
DEMOREQUEST_IP_FIELD.default_value = ""
DEMOREQUEST_IP_FIELD.type = 9
DEMOREQUEST_IP_FIELD.cpp_type = 9

DEMOREQUEST_ACCOUNTID_FIELD.name = "accountId"
DEMOREQUEST_ACCOUNTID_FIELD.full_name = ".com.demo.protobuf.DemoRequest.accountId"
DEMOREQUEST_ACCOUNTID_FIELD.number = 2
DEMOREQUEST_ACCOUNTID_FIELD.index = 1
DEMOREQUEST_ACCOUNTID_FIELD.label = 2
DEMOREQUEST_ACCOUNTID_FIELD.has_default_value = false
DEMOREQUEST_ACCOUNTID_FIELD.default_value = ""
DEMOREQUEST_ACCOUNTID_FIELD.type = 9
DEMOREQUEST_ACCOUNTID_FIELD.cpp_type = 9

DEMOREQUEST_SERVERID_FIELD.name = "serverId"
DEMOREQUEST_SERVERID_FIELD.full_name = ".com.demo.protobuf.DemoRequest.serverId"
DEMOREQUEST_SERVERID_FIELD.number = 3
DEMOREQUEST_SERVERID_FIELD.index = 2
DEMOREQUEST_SERVERID_FIELD.label = 2
DEMOREQUEST_SERVERID_FIELD.has_default_value = false
DEMOREQUEST_SERVERID_FIELD.default_value = 0
DEMOREQUEST_SERVERID_FIELD.type = 5
DEMOREQUEST_SERVERID_FIELD.cpp_type = 1

DEMOREQUEST.name = "DemoRequest"
DEMOREQUEST.full_name = ".com.demo.protobuf.DemoRequest"
DEMOREQUEST.nested_types = {}
DEMOREQUEST.enum_types = {}
DEMOREQUEST.fields = {DEMOREQUEST_IP_FIELD, DEMOREQUEST_ACCOUNTID_FIELD, DEMOREQUEST_SERVERID_FIELD}
DEMOREQUEST.is_extendable = false
DEMOREQUEST.extensions = {}
DEMORESPONSE_NAME_FIELD.name = "name"
DEMORESPONSE_NAME_FIELD.full_name = ".com.demo.protobuf.DemoResponse.name"
DEMORESPONSE_NAME_FIELD.number = 1
DEMORESPONSE_NAME_FIELD.index = 0
DEMORESPONSE_NAME_FIELD.label = 2
DEMORESPONSE_NAME_FIELD.has_default_value = false
DEMORESPONSE_NAME_FIELD.default_value = ""
DEMORESPONSE_NAME_FIELD.type = 9
DEMORESPONSE_NAME_FIELD.cpp_type = 9

DEMORESPONSE_LVL_FIELD.name = "lvl"
DEMORESPONSE_LVL_FIELD.full_name = ".com.demo.protobuf.DemoResponse.lvl"
DEMORESPONSE_LVL_FIELD.number = 2
DEMORESPONSE_LVL_FIELD.index = 1
DEMORESPONSE_LVL_FIELD.label = 2
DEMORESPONSE_LVL_FIELD.has_default_value = false
DEMORESPONSE_LVL_FIELD.default_value = 0
DEMORESPONSE_LVL_FIELD.type = 5
DEMORESPONSE_LVL_FIELD.cpp_type = 1

DEMORESPONSE.name = "DemoResponse"
DEMORESPONSE.full_name = ".com.demo.protobuf.DemoResponse"
DEMORESPONSE.nested_types = {}
DEMORESPONSE.enum_types = {}
DEMORESPONSE.fields = {DEMORESPONSE_NAME_FIELD, DEMORESPONSE_LVL_FIELD}
DEMORESPONSE.is_extendable = false
DEMORESPONSE.extensions = {}

DemoRequest = protobuf.Message(DEMOREQUEST)
DemoResponse = protobuf.Message(DEMORESPONSE)

